# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
# app/config/config.yml
liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/uno_uploads/uno_media'
        user_images_loader:
            filesystem:
                data_root: '%kernel.project_dir%/uno_uploads/user_data/images'

    driver: gd
    cache: uno_resolver
    default_filter_set_settings:
        cache: uno_resolver
    webp:
        cache: uno_resolver
        generate: true
        quality: 100

    filter_sets:
        original:
            cache: uno_resolver
            quality: 90
        user_original:
            cache: uno_resolver
            data_loader: user_images_loader
            quality: 90
        thumbnail:
            cache: uno_resolver
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: inset }
        thumbnail_large:
            cache: uno_resolver
            quality: 75
            filters:
                thumbnail: { size: [200, 200], mode: inset }
        user_thumbnail:
            cache: uno_resolver
            data_loader: user_images_loader
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: inset }