controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /admin
        permanent: true

# api/config/routes.yaml
auth:
    path: /auth
    methods: ['POST']

admin_login:
    path: /admin/login
    methods: [GET, POST]
    defaults:
      _controller: App\Controller\Admin\SecurityController::login

admin_index:
  path: /admin/
  methods: [GET, POST]
  defaults:
    _controller: App\Controller\Admin\DashboardController::index

logout:
    path: /admin/logout
    # the controller value is nulled to make this route act as a form trigger for logging out
    controller: null 

api_login_check:
    path: /api/login_check
